metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1

rpc_bind_addr = "0.0.0.0:4001"
rpc_public_addr = "0.0.0.0:4001"
rpc_secret = "a6d74b7b57ea676976e00a9839ff4c9499b376d0bc99e3ee785e1bd03bbe76c6"

[s3_api]
s3_region = "paradoxx-region"
api_bind_addr = "0.0.0.0:3900"
